### ISSUE TITLE
[BUG REPORT] Can't connect to the Polygon Mainnet Pocket Gateway: the server responded with a status of 429 (Too Many Requests) 

### ISSUE THREAD

**Issue by anon238** [buildwithgrove/portal-api#718]
**Describe the bug**
I can't connect to the Polygon Mainnet Pocket Gateway. It stays on `Connecting to Polygon Mainnet Pocket Gateway` or `Oops! Something went wrong. Try again`

**To Reproduce**
Followed this documentation: https://docs.pokt.network/home/resources/public-rpc-endpoints

**Expected behavior**
Connecting to the network.

**Screenshots**
n/a

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10
- Browser [e.g. chrome, safari] Opera GX/Chromium
- Version [e.g. 22] LVL3 (core: 83.0.4254.70)

**Smartphone (please complete the following information):**
n/a

**Additional context**
Failed to load resource: the server responded with a status of 429 (Too Many Requests)

**Comment by anon238** [comment]
got connected now.

**Comment by anon238** [comment]
reopend this one, cause it ain't fixed.

**Comment by rem1niscence** [comment]
Hey, sorry about that, dug into the issue and we had an internal db misconfig, should be fixed by now. Could you please try again? also just to confirm, you're using this polygon url (`https://poly-rpc.gateway.pokt.network/`) linked in the documentation link provided above?:

**Comment by anon238** [comment]
> Hey, sorry about that, dug into the issue and we had an internal db misconfig, should be fixed by now. Could you please try again? also just to confirm, you're using this polygon url (`https://poly-rpc.gateway.pokt.network/`) linked in the documentation link provided above?:

thanks for the heads-up! I use indeed the polygon url mentioned in the documentation, but it seems it's not up to date or something. see #717 for example. i have tried after your reply, but i have still the same issue. happy to help out tho!

**Comment by rem1niscence** [comment]
all right I'm still looking into the possible issue, will let you know shortly, thanks for the info!

**Comment by rem1niscence** [comment]
to follow up on this, are you using metamask, another wallet or connecting through a rpc client?

**Comment by anon238** [comment]
> to follow up on this, are you using metamask, another wallet or connecting through a rpc client?

Yes this is in metamask.

**Comment by anon238** [comment]
I think this is gonna help.

`Failed to load resource: the server responded with a status of 429 (Too Many Requests) https://sentry.io/api/273505/envelope/?sentry_key=3567c198f8a8412082d3265********&sentry_version=7`

```
sentry-install.js:1 Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN
sentry-install.js:1 Removing intrinsics.Object.hasOwn
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.findLast
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.findLastIndex
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLast
sentry-install.js:1 Removing intrinsics.%ArrayPrototype%.@@unscopables.findLastIndex
sentry-install.js:1 Removing intrinsics.%StringPrototype%.at
sentry-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLast
sentry-install.js:1 Removing intrinsics.%TypedArrayPrototype%.findLastIndex
sentry.io/api/273505/envelope/?sentry_key=3567c198f8a8412082d3265*********&sentry_version=7:1          Failed to load resource: the server responded with a status of 429 (Too Many Requests)
```

**Comment by rem1niscence** [comment]
ty for the data, turns out the problem is more directly related to the underlying nodes from Polygon which are blocks behind but we're currently working on that atm, will update the thread once the nodes have better caught up

**Comment by crisog** [comment]
I tried this too, and got something additional: `Unknown Infura provider type`. Unsure about the meaning of it. I was able to hit via curl in the command line pretty quick though..

**Comment by anon238** [comment]
> 

Pocket network shouldn't be affected by Infura. That's the whole point of decentralisation.

**Comment by nymd** [comment]
> I tried this too, and got something additional: `Unknown Infura provider type`. Unsure about the meaning of it. I was able to hit via curl in the command line pretty quick though..

Hey, thanks for the report but this error definitely is not from our side. Maybe it is from the library you're using to connect?

**Comment by anon238** [comment]
> ty for the data, turns out the problem is more directly related to the underlying nodes from Polygon which are blocks behind but we're currently working on that atm, will update the thread once the nodes have better caught up

there seems to be some changes made, cause i can connect immediately now. will close the ticket in a few hours when everything stays like this.

**Comment by rem1niscence** [comment]
> > ty for the data, turns out the problem is more directly related to the underlying nodes from Polygon which are blocks behind but we're currently working on that atm, will update the thread once the nodes have better caught up
> 
> there seems to be some changes made, cause i can connect immediately now. will close the ticket in a few hours when everything stays like this.

Indeed the changes to the applications and nodes were applied and service have been steady since, if you haven't feel any another service interruption yet, I'll close this issue.

**Comment by nymd** [comment]
> > ty for the data, turns out the problem is more directly related to the underlying nodes from Polygon which are blocks behind but we're currently working on that atm, will update the thread once the nodes have better caught up
> 
> there seems to be some changes made, cause i can connect immediately now. will close the ticket in a few hours when everything stays like this.

Thanks for following up!

**Comment by anon238** [comment]
thanks for the collab well done @nymd @rem1niscence
